<?php
$ModuleTemplate ['photo_list_block_header'] = "<table class=\"table-list\"><tr class=\"headings\"><td></td><td>Изображение</td></tr>";
$ModuleTemplate ['photo_list_block_bottom'] = "</table>";
$ModuleTemplate ['photo_list_block'] = "<tr><td><input type=\"radio\" value=\"#cp_photo_id#\" name=\"cp_photo_id\"/></td><td class=\"TdListLogoALignCenter\"><img src=\"../../files/images/cp/sm_#cp_photo_id#.#cp_file_type#\" alt=\"\" title=\"\"></td></tr>";
?>