<?php 
define ( 'SLASH', '/' );
define ( 'DOC_ROOT', $_SERVER ['DOCUMENT_ROOT'] );
require_once DOC_ROOT . '/dmn/utils/template.ajax/js2.css.php';
?>

<script type="text/javascript">
var id = "<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "")?>";
$(function() {
	$("#Ctabs").tabs();
	if(id == "") {
		$("#Cli-tabs-2").hide();
	}
});
</script>
<script type="text/javascript" src="../brends/js/action.collection.js"></script>
<div class="eventForm">
	<a href="#" onclick="TShowPageBrend('DMN_Brends', 'getCollections', 'BrandListCollections')" class="ui-state-default ui-corner-all bottom-padding" title="Назад" id=""><span class="ui-icon ui-icon-circle-triangle-w"></span>Назад</a> 
</div>
<div style="margin:0 10px;">
	<div id="Ctabs">
		<ul>
	    	<li><a href="#Ctabs-1">Коллекция</a></li>
	    	<li id="Cli-tabs-2"><a href="#Ctabs-2">Изображение</a></li>
	    </ul>
	    <div id="Ctabs-1">
	    	<script type="text/javascript">
				new Zapatec.Form({
					form: 'CollectionForm',
					showErrors: 'afterField',
					showErrorsOnSubmit: true,
					submitErrorFunc: testErrOutput,
					asyncSubmitFunc: OnSuccessCDataForm,
					theme: "WinXP"
				});
			</script>
	 		<form action="/dmn/t-ajax.php?zone=dmn&cont=DMN_Catalog&action=save&dataType=json" id='CollectionForm' name='DataForm' class="zpFormWinXP" method="POST">
				<fieldset>
					<label class='zpFormLabel'>Название</label> 
					<input class='zpFormRequired' value="<?php echo $Data ['ct_name']; ?>" size="40" name="ct_name" type="text"> <br />
					<label class='zpFormLabel'>Позиция</label> 
					<input value="<?php echo $Data ['pos']; ?>" name="pos" type="text" class="zpForm zpFormInt" /> <br />
				</fieldset>
				<fieldset>
					<label class='zpFormLabel'>Отображать</label> 
					<input class='zpForm' value="1" <?php echo ($Data ['hide'] ? ' checked="checked" ' : ''); ?> size="40" name="hide" type="checkbox"> <br />
				</fieldset>
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "") ;?>" size="13" name="ct_id" type="hidden"> 
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? "edit" : "new") ;?>" size="13" name="type_save" type="hidden"> 
				<input class='zpForm' value="<?php echo $parent_id;?>" size="13" name="parent_id" type="hidden"> 
				<input class='zpForm' value="4fbcb01342cf0" size="13" name="dict_id" type="hidden"> 
				<input value="Сохранить" name="Submit" onClick="" type="submit" class="button" /> 
			</form>
	  </div>
	  <div id="Ctabs-2">
			<form action="/dmn/t-ajax.php?zone=dmn&cont=DMN_Catalog&action=saveOneImage&dataType=html" enctype="multipart/form-data" id='imageCForm' class="zpFormWinXP" method="POST">
				<fieldset>
					<input class='zpForm' type="file" name="image" id="Cimage">
				</fieldset>
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "") ;?>" size="13" name="ct_id" id="imageCForm-ct_id" type="hidden"> 
				<input type="hidden" name="ct_photo_type_id" value="4fbcb5f543727" />
				<input type="hidden" name="is_small" value="false" />
				<input type="hidden" name="is_main" value="" />
				<button style="" onclick="SaveCImage('DMN_Catalog', 'saveGalleryImage')" class="" type="button" id=""><span>Сохранить</span></button>
			</form>
			<div style="margin-top:20px;" id="images-catalog-list">
				<?php if($Data ['ct_id']) { echo Controller::Template("/dmn/catalog/template/listphotos.phtml", array ('Data' => $ImageData, 'folder' => 'ct_photos' )); } ?>
			</div>
		</div>
	</div>
</div>            

