<?php 
	global $tbl;
	//формирование стран и городов
	$dictionaries = new dictionaries ( );
	$dictionaries->buid_dictionaries_list ( $tbl ['list_dict'] ['name'] );
	$dictionaries->buid_dictionaries ( $tbl ['dict'] ['name'], "WHERE lang_id = {$_COOKIE['lang_id']} ORDER BY dict_name ASC" );
	$dictionaries->do_dictionaries ( 12);
	$newsTypeDict = $dictionaries->my_dct;
?>
<div class="eventForm">
	<a href="#" onclick="TAddBrend('DMN_Brends', 'getCollection', 'BrandListCollections');" class="ui-state-default ui-corner-all bottom-padding" title="Добавить коллекцию" id="submitNAdd"><span class="ui-icon ui-icon-plus"></span>Добавить коллекцию</a> 
</div>
<?php if ($Data) : ?>
<table class="table-list" cellspacing="0" cellpadding="0" border="0">
	<tr class="headings">
		<td width=10></td>
		<td width=50>ID</td>
		<td>Название</td>
		<td>Ссылка</td>
		<td width=150>Дата добавления</td>
		<td width=80>Позиция</td>
		<td width=80>Активность</td>
		<td width="150"></td>
	</tr>
	<tbody>
		<?php foreach ( $Data as $key => $value ) : ?>
		<tr>
			<td></td>
			<td><?php echo $value["ct_id"]?></td>
			<td><?php echo $value["ct_name"]?></td>
			<td><?php echo $value["ct_url"]?></td>
			<td><?php echo $value["date"]?></td>
			<td><?php echo $value["pos"]; ?></td>
			<td><?php echo ($value["hide"] ? "Да" : "Нет");?></td>
			<td><a href="#" onclick="TBrendsEdit('DMN_Brends', 'getCollection', '<?php echo $value["ct_id"]?>', 'BrandListCollections')" title="Просмотр/Редактирование">Просмотр/Редактирование</a> 
			<a href="#" onclick="TBrendsDelete('DMN_Brends', 'deleteCollection', '<?php echo $value["ct_id"]?>', 'BrandListCollections')" title="Удалить">Удалить</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<b>Ничего не найдено по Вашему запросу!</b>
<?php endif; ?>