<?php 
	global $tbl;
	//формирование стран и городов
	$dictionaries = new dictionaries ( );
	$dictionaries->buid_dictionaries_list ( $tbl ['list_dict'] ['name'] );
	$dictionaries->buid_dictionaries ( $tbl ['dict'] ['name'], "WHERE lang_id = {$_COOKIE['lang_id']} ORDER BY dict_name ASC" );
	$dictionaries->do_dictionaries ( 12);
	$newsTypeDict = $dictionaries->my_dct;
	

?>
<?php if ($Data) : ?>
<table class="table-list" cellspacing="0" cellpadding="0" border="0">
	<tr class="headings">
		<td width=10></td>
		<td width=50>ID</td>
		<td width=100>Изображение</td>
		<td>Бренд</td>
		<td>Ссылка</td>
		<td width=150>Дата добавления</td>
		<td width=80>Позиция</td>
		<td width=80>Активность</td>
		<td width="150"></td>
	</tr>
	<tbody>
		<?php foreach ( $Data as $key => $value ) : ?>
		<tr>
			<td></td>
			<td><?php echo $value["ct_id"]?></td>
			<td style="background: #192129"><?php if($value["ct_photo_id"]):?><img width="100" src="../../files/images/ct_photos/<?php echo $value["ct_photo_id"]?>.<?php echo $value["ct_photo_file_type"]?>"/><?php endif;?></td>
			<td><?php echo $value["ct_name"]?></td>
			<td><?php echo $value["ct_url"]?></td>
			<td><?php echo $value["date"]?></td>
			<td><?php echo $value["pos"]; ?></td>
			<td><?php echo ($value["hide"] ? "Да" : "Нет");?></td>
			<td><a href="#" onclick="TEdit('DMN_Brends', 'getBrend', '<?php echo $value["ct_id"]?>')" title="Просмотр/Редактирование">Просмотр/Редактирование</a> <a href="#" onclick="TDelete('DMN_Brends', 'delete', '<?php echo $value["ct_id"]?>')" title="Удалить">Удалить</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<b>Ничего не найдено по Вашему запросу!</b>
<?php endif; ?>