<?php 
	global $tbl;
	//формирование стран и городов
	$dictionaries = new dictionariesClass ( );
	$dictionaries->buid_dictionaries_list ( $tbl ['list_dict'] ['name'] );
	$dictionaries->buid_dictionaries ( $tbl ['dict'] ['name'], "WHERE lang_id = {$_COOKIE['lang_id']} ORDER BY dict_name ASC" );
	$dictionaries->do_dictionaries ( 12);
	$newsTypeDict = $dictionaries->my_dct;
?>
<?php if ($Data) : ?>
<table class="table-list" cellspacing="0" cellpadding="0" border="0">
	<tr class="headings">
		<td width="10"></td>
		<td width="150">Изображение</td>
		<td width="150">Заголовок</td>
		<td width="120">Ссылка</td>
		<td width="70">Дата</td>
		<td width="70">На главной</td>
		<td width="70">Показывать</td>
		<td width="150"></td>
	</tr>
	<tbody>
		
		<?php foreach ( $Data as $key => $value ) : ?>
		<tr>
			<td width="10"><?php echo $value["news_id"]?></td>
			<td><?php if($value["ct_photo_id"]):?><img width="100" src="../../files/images/news/<?php echo $value["ct_photo_id"]?>.<?php echo $value["ct_photo_file_type"]?>"/><?php endif;?></td>
			<td><?php echo $value["news_title"]?></td>
			<td><?php echo $value["news_url"]?></td>
			<td><?php echo $value["news_date"]?></td>
			<td><?php echo ($value["is_show_index"] ? "Да" : "Нет")?></td>
			<td><?php echo ($value["hide"] == "show" ? "Да" : "Нет")?></td>
			<td><a href="#" onclick="TEdit('DMN_News', 'getNews', '<?php echo $value["news_id"]?>')" title="Просмотр/Редактирование">Просмотр/Редактирование</a> <a href="#" onclick="TDelete('DMN_News', 'delete', '<?php echo $value["news_id"]?>')" title="Удалить">Удалить</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<b>No data!</b>
<?php endif; ?>


