<?php if ($Data) : ?>
<table class="table-list" cellspacing="0" cellpadding="0" border="0">
	<tr class="headings">
		<td width="10"></td>
		<td width="350">Name</td>
		<td width="150">Catalog</td>
		<td width="5">Date</td>
		<td width="50">Time</td>
		<td width="150">Place</td>
		<td width="100">Country</td>
		<td width="100">City</td>
		<td width="100">Active</td>
		<td width="50"></td>
	</tr>
	<tbody>
		
		<?php foreach ( $Data as $key => $value ) : ?>
		<tr>
			<td width="10"><?php echo $value["ga_id"]?></td>
			<td><?php echo $value["ga_name"]?></td>
			<td><?php echo $value["ct_name"]?></td>
			<td><?php echo $value["ga_date"]?></td>
			<td><?php echo $value["ga_time"]?></td>
			<td><?php echo $value["place"]?></td>
			<td><?php echo $value["country"]?></td>
			<td><?php echo $value["city"]?></td>
			<td><?php echo ($value["hide"] ? "Yes" : "No")?></td>
			<td ><a href="#" onclick="TEdit('DMN_GoodsAction', 'getGoodsAction', <?php echo $value["ga_id"]?>)" title="edit">Edit</a> <a href="#" onclick="TDelete('DMN_GoodsAction', 'delete', <?php echo $value["ga_id"]?>)" title="Delete">Delete</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<b>No data!</b>
<?php endif; ?>


