<?php 
define ( 'SLASH', '/' );
define ( 'DOC_ROOT', $_SERVER ['DOCUMENT_ROOT'] );
require_once DOC_ROOT . '/dmn/utils/template.ajax/js2.css.php';
 
global $tbl;
//формирование стран и городов
$dictionaries = new dictionaries ( );
$dictionaries->buid_dictionaries_list ( $tbl ['list_dict'] ['name'] );
$dictionaries->buid_dictionaries ( $tbl ['dict'] ['name'], "WHERE lang_id = {$_COOKIE['lang_id']} ORDER BY dict_name ASC" );
$dictionaries->do_dictionaries ( 33 );
$cityDict = $dictionaries->my_dct;
$dictionaries->do_dictionaries ( 82 );
$typeImages = $dictionaries->my_dct;
?>

<script type="text/javascript">
var id = "<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "")?>";
$(function() {
	$("#tabs").tabs();
	if(id == "") {
		$("#li-tabs-2").hide();
	}
});
</script>
<script type="text/javascript" src="../shops/js/action.js"></script>
<div class="eventForm">
	<a href="#" onclick="TShowPage('DMN_Shops', 'getPage')" class="ui-state-default ui-corner-all bottom-padding" title="Назад" id=""><span class="ui-icon ui-icon-circle-triangle-w"></span>Назад</a> 
</div>
<div style="margin:0 10px;">
	<div id='errOutputGood' class="errOutputGood"></div>
	<div id='errOutput' class="errOutput"></div>
	<div id="tabs">
		<ul>
	    	<li><a href="#tabs-1">Информация</a></li>
	    	<li id="li-tabs-2"><a href="#tabs-2">Изображения</a></li>
	    </ul>
	    <div id="tabs-1">
	    	<script type="text/javascript">
				new Zapatec.Form({
					form: 'DataForm',
					showErrors: 'afterField',
					showErrorsOnSubmit: true,
					submitErrorFunc: testErrOutput,
					asyncSubmitFunc: OnSuccessDataForm,
					theme: "WinXP"
				});
			</script>
	 		<form action="/dmn/t-ajax.php?zone=dmn&cont=DMN_Shops&action=save&dataType=json" id='DataForm' name='DataForm' class="zpFormWinXP" method="POST">
				<fieldset>
					<legend>Мета данные</legend>
					<label class='zpFormLabel'>Веб заголовок</label> 
					<input class='zpForm' value="<?php echo $Data ['ct_w_title'];?>" size="40" name="ct_w_title" type="text"> <br />
					<label class='zpFormLabel'>Веб ключевые слова</label> 
					<input class='zpForm' value="<?php echo $Data ['ct_w_keywords'];?>" size="40" name="ct_w_keywords" type="text"> <br />
					<label class='zpFormLabel'>Веб описание</label> 
					<input class='zpForm' value="<?php echo $Data ['ct_w_description'];?>" size="40" name="ct_w_description" type="text"> <br />
				</fieldset>
				<fieldset>
					<label class='zpFormLabel'>Текст</label> <br /> 
					<textarea class='zpForm' rows="10" cols="10" name="ct_text"><?php echo $Data ['ct_text']; ?></textarea><br /> 
					<label class='zpFormLabel'>Адрес</label> 
					<input class='zpFormRequired' value="<?php echo $Data ['ct_description'];?>" size="60" name="ct_description" type="text"> <br />
				</fieldset>
				<fieldset>
					<label class='zpFormLabel'>Бренд</label> 
					<select name="brand_id" class="zpFormRequired">
						<?php echo sel_parent_id ( $brandsParent,  $Data ['brand_id'], 'ct_id', 'ct_name' ); ?>
					</select>
					<br />
					<label class='zpFormLabel'>Город</label> 
					<select name="city_id" class="zpFormRequired">
						<?php echo sel_parent_id ( $cityDict, $Data ['city_id'], 'dict_id', 'dict_name' ); ?>
					</select>
					<br />
				</fieldset>
				<fieldset>
					<label class='zpFormLabel'>Позиция</label> 
					<input value="<?php echo $Data ['pos']; ?>" name="pos" type="text" class="zpForm zpFormInt" /> <br />
					<label class='zpFormLabel'>Отображать</label> 
					<input class='zpForm' value="1" <?php echo ($Data ['hide'] ? ' checked="checked" ' : ''); ?> <?php echo ($Data ['ct_id'] ? "" : ' checked="checked" ') ;?> size="40" name="hide" type="checkbox"> <br />
				</fieldset>
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "") ;?>" size="13" name="ct_id" type="hidden"> 
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? "edit" : "new") ;?>" size="13" name="type_save" type="hidden"> 
				<input class='zpForm' value="1000000000000" size="13" name="parent_id" type="hidden"> 
				<input class='zpForm' value="4fb0f701c0e1f" size="13" name="dict_id" type="hidden"> 
				<input value="Сохранить" name="Submit" onClick="" type="submit" class="button" /> 
			</form>
	  </div>
	  <div id="tabs-2">
			<form action="/dmn/t-ajax.php?zone=dmn&cont=DMN_Catalog&action=saveOneImage&dataType=html" enctype="multipart/form-data" id='imageForm' class="zpFormWinXP" method="POST">
				<fieldset>
					<input class='zpForm' type="file" name="image" id="image">
					<br />
					<label class='zpFormLabel'>Тип изображения</label> <br />
					<select onChange="changeMainImage();" name="ct_photo_type_id" id="image_ct_photo_type_id" class="zpFormRequired">
						<?php echo sel_parent_id ( $typeImages, '', 'dict_id', 'dict_name' ); ?>
					</select>
					<br />
				</fieldset>
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "") ;?>" size="13" name="ct_id" id="imageForm-ct_id" type="hidden"> 
				<input type="hidden" name="is_small" value="false" />
				<input type="hidden" name="is_main" id="is_main" value="1" />
				<input type="hidden" name="folder" value="shops"/>
				<button style="" onclick="SaveImage('DMN_Catalog', 'saveGalleryOneImage')" class="" type="button" id=""><span>Сохранить</span></button>
			</form>
			<div style="margin-top:20px;" id="images-list">
				<?php if($Data ['ct_id']) { echo Controller::Template("/dmn/shops/template/listphotos.phtml", array ('Data' => $ImageData )); } ?>
			</div>
		</div>
	</div>
</div>            

