<?php if ($Data) : ?>
<table class="table-list" cellspacing="0" cellpadding="0" border="0">
	<tr class="headings">
		<td width=10></td>
		<td width=50>ID</td>
		<td width=100>Изображение</td>
		<td width=80>Бренд</td>
		<td width=80>Город</td>
		
<!--		<td>Название</td>-->
<!--		<td>Заголовок</td>-->
		<td width=150>Дата добавления</td>
		<td width=80>Позиция</td>
		<td width=80>Активность</td>
		<td width=150>Тип</td>
	</tr>
	<tbody>
		<?php foreach ( $Data as $key => $value ) : ?>
		<tr>
			<td></td>
			<td><?php echo $value["ct_id"]?></td>
			<td><?php if($value["ct_photo_id"]):?><img width="100" src="../../files/images/shops/<?php echo $value["ct_photo_id"]?>.<?php echo $value["ct_photo_file_type"]?>"/><?php endif;?></td>
			<td><?php echo $value["brand_name"]; ?></td>
			<td><?php echo $value["dict_name"]; ?></td>
			<!--<td><?php echo $value["ct_name"]?></td>
			<td><?php echo $value["ct_title"]?></td>
			--><td><?php echo $value["date"]?></td>
			<td><?php echo $value["pos"]; ?></td>
			<td><?php echo ($value["hide"] ? "Да" : "Нет")?></td>
			<td><a href="#" onclick="TEdit('DMN_Shops', 'getShop', '<?php echo $value["ct_id"]?>')" title="Просмотр/Редактирование">Просмотр/Редактирование</a> <a href="#" onclick="TDelete('DMN_Shops', 'delete', '<?php echo $value["ct_id"]?>')" title="Удалить">Удалить</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<b>Ничего не найдено по Вашему запросу!</b>
<?php endif; ?>