<?php 
define ( 'SLASH', '/' );
define ( 'DOC_ROOT', $_SERVER ['DOCUMENT_ROOT'] );
require_once DOC_ROOT . '/dmn/utils/template.ajax/js2.css.php';
?>

<script type="text/javascript">
var id = "<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "")?>";
$(function() {
	$("#tabs").tabs();
	if(id == "") {
		$("#li-tabs-2").hide();
	}
});
</script>
<script type="text/javascript" src="../brends/js/action.js"></script>
<div class="eventForm">
	<a href="#" onclick="TShowPage('DMN_Visa', 'getPage')" class="ui-state-default ui-corner-all bottom-padding" title="Назад" id=""><span class="ui-icon ui-icon-circle-triangle-w"></span>Назад</a> 
</div>
<div style="margin:0 10px;">
	<div id='errOutputGood' class="errOutputGood"></div>
	<div id='errOutput' class="errOutput"></div>
	<div id="tabs">
		<ul>
	    	<li><a href="#tabs-1">Visa</a></li>
	    	<li id="li-tabs-2"><a href="#tabs-2">Изображения</a></li>
	    </ul>
	    <div id="tabs-1">
	    	<script type="text/javascript">
				new Zapatec.Form({
					form: 'DataForm',
					showErrors: 'afterField',
					showErrorsOnSubmit: true,
					submitErrorFunc: testErrOutput,
					asyncSubmitFunc: OnSuccessDataForm,
					theme: "WinXP"
				});
			</script>
	 		<form action="/dmn/t-ajax.php?zone=dmn&cont=DMN_Catalog&action=save&dataType=json" id='DataForm' name='DataForm' class="zpFormWinXP" method="POST">
				<fieldset>
					<label class='zpFormLabel'>Заголовок</label> 
					<input class='zpFormRequired' value="<?php echo $Data ['ct_title']; ?>" size="40" name="ct_title" type="text"> <br />
					<label class='zpFormLabel'>Позиция</label> 
					<input value="<?php echo $Data ['pos']; ?>" name="pos" type="text" class="zpForm zpFormInt" /> <br />
					<label class='zpFormLabel'>Подробное описание</label> <br /> 
					<textarea class='zpForm' rows="10" cols="10" name="ct_text"><?php echo $Data ['ct_text']; ?></textarea><br /> 
				</fieldset>
				<fieldset>
					<label class='zpFormLabel'>Отображать</label> 
					<input class='zpForm' value="1" <?php echo ($Data ['hide'] ? ' checked="checked" ' : ''); ?> size="40" name="hide" type="checkbox"> <br />
				</fieldset>
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "") ;?>" size="13" name="ct_id" type="hidden"> 
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? "edit" : "new") ;?>" size="13" name="type_save" type="hidden"> 
				<input class='zpForm' value="1000000000000" size="13" name="parent_id" type="hidden"> 
				<input class='zpForm' value="4fb609173b483" size="13" name="dict_id" type="hidden"> 
				<input value="Сохранить" name="Submit" onClick="" type="submit" class="button" /> 
			</form>
	  </div>
	  <div id="tabs-2">
			<form action="/dmn/t-ajax.php?zone=dmn&cont=DMN_Catalog&action=saveOneImage&dataType=html" enctype="multipart/form-data" id='imageForm' class="zpFormWinXP" method="POST">
				<fieldset>
					<input class='zpForm' type="file" name="image" id="image">
				</fieldset>
				<input class='zpForm' value="<?php echo ($Data ['ct_id'] ? $Data ['ct_id'] : "") ;?>" size="13" name="ct_id" id="imageForm-ct_id" type="hidden"> 
				<input type="hidden" name="ct_photo_type_id" value="4d05c24dc8477" />
				<input type="hidden" name="is_small" value="false" />
				<input type="hidden" name="is_main" value="1" />
				<button style="" onclick="SaveImage('DMN_Catalog', 'saveOneImage')" class="" type="button" id=""><span>Сохранить</span></button>
			</form>
			<div style="margin-top:20px; background: #192129" id="images-list">
				<?php if($ImageData["ct_photo_id"]) :?>
					<div class="image-<?php echo $ImageData["ct_photo_id"]?>">
						<img  src="../../files/images/ct_photos/sm_<?php echo $ImageData["ct_photo_id"]?>.<?php echo $ImageData["ct_photo_file_type"]?>"/> 
						<a title="Удалить" style="color:#FFF" onclick="TDeleteImage('DMN_Catalog', 'deleteImage', '<?php echo $ImageData["ct_photo_id"]?>')" href="#">Удалить</a>
					</div>
				<?php endif;?>
		   	</div>
		</div>
	</div>
</div>            

