<?php 
#
$tbl ['list_dict'] ['name'] = $tbl_list_dictionaries = 'list_dictionaries';
$tbl ['list_dict'] ['order'] = "";
$tbl ['list_dict'] ['limit'] = "";
#
$tbl ['dict'] ['name'] = $tbl_dictionaries = 'dictionaries';
$tbl ['dict'] ['order'] = "";
$tbl ['dict'] ['limit'] = "";
#
$tbl ['modules'] ['name'] = $tbl_modules = 'modules';
$tbl ['modules'] ['order'] = "";
$tbl ['modules'] ['limit'] = "";
#
$tbl ['templates'] ['name'] = $tbl_temp = 'templates';
$tbl ['templates'] ['order'] = "";
$tbl ['templates'] ['limit'] = "";
#
$tbl ['pages'] ['name'] = $tbl_pages = 'pages';
$tbl ['pages'] ['order'] = "";
$tbl ['pages'] ['limit'] = "";
#
$tbl ['pages_structure'] ['name'] = $tbl_sturture = ' pages_structure';
$tbl ['pages_structure'] ['order'] = "";
$tbl ['pages_structure'] ['limit'] = "";
#
$tbl ['pages_content'] ['name'] = $tbl_content = ' pages_content';
$tbl ['pages_content'] ['order'] = "";
$tbl ['pages_content'] ['limit'] = "";
#
$tbl ['ptm'] ['name'] = $tbl_ptm = 'pages_temp_mod';
$tbl ['ptm'] ['order'] = "";
$tbl ['ptm'] ['limit'] = "";
#
$tbl ['pages_module'] ['name'] = $tbl_pages_module = 'pages_module';
$tbl ['pages_module'] ['order'] = "";
$tbl ['pages_module'] ['limit'] = "";
#
$tbl ['lang'] ['name'] = $tbl_lang = 'language';
$tbl ['lang'] ['order'] = "";
$tbl ['lang'] ['limit'] = "";
#
$tbl ['temp_module'] ['name'] = $tbl_temp_module = 'templates_modules';
$tbl ['temp_module'] ['order'] = "";
$tbl ['temp_module'] ['limit'] = "";
#
$tbl ['catalog'] ['name'] = $tbl_catalog = 'catalog';
$tbl ['catalog'] ['order'] = "date desc";
$tbl ['catalog'] ['limit'] = "";
$tbl ['catalog'] ['id'] = "ct_id";
#
$tbl ['ct_connection'] ['name'] = $tbl_ct_connection = 'ct_connection';
$tbl ['ct_connection'] ['order'] = "";
$tbl ['ct_connection'] ['limit'] = "";
#
$tbl ['ct_photos'] ['name'] = $tbl_ct_photos = 'ct_photos';
$tbl ['ct_photos'] ['order'] = "ct_photo_order";
$tbl ['ct_photos'] ['limit'] = "";
#
$tbl ['cp'] ['name'] = $tbl_cp = 'cp_goods';
$tbl ['cp'] ['order'] = "cp_date_add";
$tbl ['cp'] ['limit'] = "20";
#
$tbl ['cc'] ['name'] = $tbl_cc = 'cp_codes';
$tbl ['cc'] ['order'] = "";
$tbl ['cc'] ['limit'] = "";
#
$tbl ['news'] ['name'] = $tbl_news = 'news';
$tbl ['news'] ['order'] = "news_date";
$tbl ['news'] ['limit'] = "10";
#
$tbl ['news_img'] ['name'] = $tbl_news_img = 'news_img';
$tbl ['news_img'] ['order'] = "pos";
$tbl ['news_img'] ['limit'] = "";
#
$tbl ['partners'] ['name'] = $tbl_partners = 'partner';
$tbl ['partners'] ['order'] = "pos";
$tbl ['partners'] ['limit'] = "";
#
$tbl ['users_site'] ['name'] = $tbl_users_site = 'users_site';
$tbl ['users_site'] ['order'] = "";
$tbl ['users_site'] ['limit'] = "";
#
$tbl ['company'] ['name'] = $tbl_users_site = 'company_info';
$tbl ['company'] ['order'] = "";
$tbl ['company'] ['limit'] = "";
$tbl ['company'] ['id'] = "user_id";