<?php if (count($Data) > 0)  : ?>
<table class="table-list" cellspacing="0" cellpadding="0" border="0">
	<tr class="headings">
		<td width=100>Цена</td>
		<td width=150>Тип</td>
		<td width=150></td>
	</tr>
	<tbody>
		<?php foreach ( $Data as $key => $value ) : ?>
		<tr>
			<td><?php echo $value["tour_prices"]?></td>
			<td><?php echo $Model->dictionaries->buld_table[$value["type_id"]]["dict_name"]; ?></td>
			<td><a href="#" onclick="TDelete('DMN_Tours', 'deletePrice', '<?php echo $value["tour_prices_id"]?>', '&tour_id=<?php echo $value["tours_tour_id"]?>', 'price-list')" title="Удалить">Удалить</a></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<b>Ничего не найдено по Вашему запросу!</b>
<?php endif; ?>
